### ISSUE TITLE
Button to select app/content type not coming up

### ISSUE THREAD

**Issue by Tychodewaard** [2sic/2sxc#1575]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 
[x] not sure

**...about**   
[x] edit experience / UI

**Current behavior**
I have a customer (admin rights) who has exactly the same Chrome version (66.0.3359.181) but does not see the blue glass button after adding a app/content module to a page. I created an account with the same rights and tested on my laptop and everything works fine. Because she shared her screen using skype, I seen this myself otherwise I douldn't have believed it. She can she the container action buttons from DNN but the 2SXC blue button is not coming up. If I fill the module with content, she can see the 3 buttons

**Expected behavior**

After adding an app/content module, the customer gets an option to selct the app or content type

**Minimal reproduction of the problem with instructions**
I can not reproduce myself, so hope you have an explanation or other people with the same issue

**What is the motivation / use case for changing the behavior?**
This behaviour changed yesterday. 9.14 LTS was working as expected but since the tool box was not working 100% with long content, I upgraded to 9.32 LTS. And now this behaviour started.

**Please tell us about your environment:**
DNN 804, English

**Comment by iJungleboy** [comment]
I'm guessing it's a caching issue - basically some css/js updated and she's still getting the old version. I would ctl+f5 before trying anything else.

**Comment by Tychodewaard** [comment]
We tried incognito on different computers and networks but it still doesn't come up. What I just found out is that the content module is working as expected but the app module is the one with troubles. And as it works fine on my end, could it be permission related?

**Comment by iJungleboy** [comment]
In this case I'm going to guess that it's something specific with your app. Does it happen on other apps? especially an a trivial standard app like the qr-code? or just on this one, probably custom app?

**Comment by Tychodewaard** [comment]
They don't get to that point. They add the app module to a pane and it stops there. There is no blue button with glass icon for them to select an app.
I always install the app module with only the default 'Accordeon app' to ensure that all is initialized/installed well. And than add quite simple token apps to offer easy management of beautiful content. 
After they added the module, they only see the black DNN icons. If I go to the same page, I do see the blue button and I can select the apps.

**Comment by iJungleboy** [comment]
can you clarify: as it doesn't happen to you, is the issue tied to the user (so it appears on other pcs/browsers with same login) or the PC?

**Comment by iJungleboy** [comment]
As I presume this is not a 2sxc bug, but something in your setup, I'll close it as an issue. If you have further questions, you can post them here, but I assume if you use that login on another PC you'll see the same, and then be able to find out what is different. My guess is it's a 'div' or something not closing because of some if-condition for certain users/groups.

**Comment by Tychodewaard** [comment]
I'm a bit further: it appears it happens for all admins. The issue is not for hosts. 
As admin I can add the App module but I can not select the app. The Content module works as expected.

If I click on 'app management', I see in the console:
VM2232:1 Uncaught ReferenceError: $2sxcActionMenuMapper is not defined
    at <anonymous>:1:1
Clicking n VM 2232:1 it says: $2sxcActionMenuMapper(1106).adminZone();

FYI: I have created token apps only. So, just bootstrap snippets that get injected with 2SXC tokens.

**Comment by iJungleboy** [comment]
Just guessing but I think it's a DNN client-dependency issue. Please increase the number or disable it temporarily, to see if that would fix it.

**Comment by Tychodewaard** [comment]
Nope: emptied cache, restarted, increased the number (minification etc was already not active), emptied cache again, restarted again and....same thing. So that did not solve it.

**Comment by Tychodewaard** [comment]
I now granted the customer Host access, so it is definitely permission related. As the recent versions had security overhauls, could it be that ot has something to do with that?

**Comment by iJungleboy** [comment]
I don't think so. Basically I can take another site, give / remove admin rights, and things behave correctly. Buttons appear and go away. And permissions should behave the same on app & content, so I don't think so. Please try to find out what is different in the output: 

1. Does the menu-metadata get added or not (it's a json in an attribute)? 
2. Do the JS get included, and is it in the right order?
3. Does another JS error (maybe not in 2sxc) stop jquery from running all scripts?

**Comment by Tychodewaard** [comment]
What I notidced: there is 1 app that throws an error when you try to export it. I wanted to import every app seperately to discover if an app was causing trouble and if so, what app. The other apps export without issue. The error when exporting the "table app" I created:

System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Tracing.Tracers.HttpControllerTracer.<ExecuteAsyncCore>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()An error has occurred.The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.System.IO.PathTooLongException at System.IO.PathHelper.GetFullPathName() at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths) at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths) at System.IO.Path.GetFullPathInternal(String path) at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost) at System.IO.File.Copy(String sourceFileName, String destFileName) at ToSic.Eav.Apps.ImportExport.ZipExport.ExportApp(Boolean includeContentGroups, Boolean resetAppGuid)

The token app consists of 6 fields, all 6 string.
There are 4 views utilizing different number of columns. The 2 column view has a template like:
<table class="table table-bordered table-hover">

  <tbody>
      <repeat>
          
    <tr>
      <td>[Content:Toolbar][Content:Col1]</td>
      <td>[Content:Col2]</td>
    </tr>
    </repeat>
  </tbody>
</table>

The 3 column view template looks like:
<table class="table table-bordered table-hover">

  <tbody>
      <repeat>
          
    <tr>
      <td>[Content:Toolbar][Content:Col1]</td>
      <td>[Content:Col2]</td>
      <td>[Content:Col3]</td>
    </tr>
    </repeat>
  </tbody>
</table>

For 4 and 5 columns it is simular

**Comment by Tychodewaard** [comment]
The error mentions something is too long.
The App is called: Tables
The views Tables2Col, Tables3Col etc
The fields are Col1, Col2 etc

So, that looks short enough.

**Comment by iJungleboy** [comment]
Basically you should reduce your test-case. Just put one app on a page (any app that causes the issue) and then see how the HTML or loaded JS is different from admin-only to host. That should give you the core problem.

**Comment by iJungleboy** [comment]
Yes, this could be related to 9.32. Could you update to 9.32 RC (there were 2-3 minor fixes) just to check. Could I maybe also get host-access so I can read the internal logs to see where the security-checks decide it's not ok?

**Comment by Tychodewaard** [comment]
I think the best way forward is that I create 2 accounts for you: 1 admin, 1 host.
That way you can first see the log yourself. And then I'll upgrade.
Can you email me your Skype or Whatsapp to info@tjeps.com? That way I can pass on the credentials.

**Comment by Tychodewaard** [comment]
I just installed th 9.32-RC and that fixes the issue on the test-version.
Do you still wish access for further investigation?

**Comment by Tychodewaard** [comment]
On the live site the issue still persists. I'll elaborate via email.

**Comment by iJungleboy** [comment]
So if I understand it correctly, with 9.32 Pre1 the issue exists, but it's solved in 9.32 RC. Because if this is the case, I won't persue it any further. ok?

**Comment by Tychodewaard** [comment]
Well, the live site is now on 9.32-RC as well and the issue still exists on that one. 
You have urls and credentials in your email. Would be truly appreciated if you could spare a moment.

**Comment by iJungleboy** [comment]
@Tychodewaard I found the problem - yes! it was an issue with the new permission checks. Sorry for this, and thanks for your perseverance! 
I'll release another RC in a few hours and it should fix the problem.

**Comment by MarNothing** [comment]
Just tried it, and it seems to be fixed indeed...

**Comment by Tychodewaard** [comment]
Great, thnx!
This one can be closed.
