### ISSUE TITLE
BUG: Error saving item when library of files is required field

### ISSUE THREAD

**Issue by tpperlman** [2sic/2sxc#1825]
**I'm submitting a ...** 
[x] bug report

**...about**
[x] edit experience / UI
[x] admin experience UI

**Current behavior**
If a library of files is added to a content type and marked as required, you cannot save the item regardless whether you have added one or more files. The error says, "To save the form, please fix the following errors: Images: required."

**Expected behavior**
If you have uploaded one or more files, the item should save.

**Minimal reproduction of the problem with instructions**
Create a new content type with a library of files. Mark the field as required. Create a new item adding one or more files and then click save. Notice the error that appears.

**What is the motivation / use case for changing the behavior?**
None

**Please tell us about your environment:**
Windows 10

* **2sxc version(s):** 10.5.0
* **Browser:** Chrome 77.0.3865.90, Firefox 69.0.1
* **DNN:** 9.4.0
* **Language:** English

**Comment by iJungleboy** [comment]
I believe this is fixed. could you verify?

**Comment by tpperlman** [comment]
I just tested 2sxc v10.21 on DNN v9.4.4 and the issue remains. I created a new content type with a text input and library of files. When I enter content into both, I am still prompted to add files:

![2sxc-library](https://user-images.githubusercontent.com/1871915/70639374-63543300-1c08-11ea-926d-e6d31741426a.jpg)

**Comment by PagnoDunadan** [comment]
Fixed in next version. https://github.com/2sic/eav-item-dialog-angular/issues/154
