### ISSUE TITLE
Change Template control not responding

### ISSUE THREAD

**Issue by ajplopez** [2sic/2sxc#2048]
**I'm submitting a ...** 
[x] bug report

**...about** 
[x] admin experience UI

**Current behavior**

As an admin, while in edit mode in DNN, if I hover over the module settings pencil and click "Change Template / Layout", nothing happens.

**Expected behavior**

The Change Layout / Template panel at the bottom of the screen should appear.

**Minimal reproduction of the problem with instructions**
1. Go into edit mode. 
2. Hover over the pencil icon on a 2sxc Content module
3. In the dropdown, click "Change Template / Layout"
4. Notice how nothing appears

**What is the motivation / use case for changing the behavior?**
I want to change the module's 2sxc template

**Please tell us about your environment:**

* **2sxc version(s):** 10.28.0  
* **Browser:** [Chrome]
* **DNN:** [9.3.2 ] 
* **Language:** [English]

**Anything you would like to add**

![Screen Shot 2020-04-20 at 11 17 59 AM](https://user-images.githubusercontent.com/8751936/79785641-06c0fd00-82f9-11ea-8029-cfb560f7ead7.png)

![Screen Shot 2020-04-20 at 11 21 24 AM](https://user-images.githubusercontent.com/8751936/79785669-16404600-82f9-11ea-8d66-545c09a9a5bd.png)

**Comment by iJungleboy** [comment]
same as #2045 - should be fixed tonight or tomorrow.
I won't close this now, because 3-4 people reported the same thing ;)

**Comment by iJungleboy** [comment]
fixed, pls test 10.29 ;)

**Comment by ajplopez** [comment]
After upgrading to 10.29, I'm still seeing the issue where I can't change the layout. The layout switcher doesn't appear. Here's a screenshot of errors in the console.

![Screen Shot 2020-04-20 at 3 20 00 PM](https://user-images.githubusercontent.com/8751936/79805181-6c71b100-831a-11ea-9a93-07c3381db7cf.png)

**Comment by ajplopez** [comment]
I've tried clearing browser cache, opening a new browser, clearing cache, and trying again and it still doesn't work - I'm still getting the "$2sxcActionMenuMapper is not defined" error in the console. I also tried a repair install of the module but that didn't make a difference.

Not sure if it makes a difference, but I'm using the Content module, not the App module.

**Comment by iJungleboy** [comment]
Thanks for the feedback. I can reproduce it!
This is the connection between the dnn-buttons and the actions. I believe evrything else works, but let me fix this asap.

**Comment by iJungleboy** [comment]
should be fixed now in latest release, thanks for the feedback
