### ISSUE TITLE
Various issues with the turkish language

### ISSUE THREAD

**Issue by MS-BSI** [2sic/2sxc#2261]
**I'm submitting a ...** 
[x] bug report

**...about** 
[x] admin experience UI
[x] other / unknown

**Current behavior**
After a big upgrade from 2SXC 10.X to 11.10.01, we have a lot of strange issues on a turkish website. All the others websites (in many languages) in the same DNN instance seem to be OK.

In order to debug we have installed the Turkish language on a functional site and all of our 2SXC Content modules present the same problems.
For example, and this is probably the easiest to observe, "select" listboxes in the backoffice of a Content module aren't displayed, instead a simple "input field" is shown.
If you go through another language (English page for example) and try to access the Turkish language entry form (via the top tabs) then everything is OK.
Stranger, if you load the site in English and load the Turkish site in **another tab** and then try to modify the content of a 2SXC Content module of the EN website, that doesn't work either.

**Expected behavior**
Same behavior than other languages.

* **2sxc version(s):** 11.10.01
* **Browser:** [all]
* **DNN:** [8.0.4] 
* **Language:** [Turkish website but english UI language]

**Comment by iJungleboy** [comment]
I have a few guesses but could you add some screenshots - incl. the global 2sxc-language settings and dnn-language settings? + how a turkish UI fails?

**Comment by MS-BSI** [comment]
Yes, this is the reason why I had opened [this other ticket](https://github.com/2sic/2sxc/issues/2260), not being able to verify the 2SXC language information. I made the requested changes by removing 3 entries (out of 4 visible entries) but it does not seem to have given anything.

Is this normal ?
https://i.imgur.com/npFnR3I.png

Same thing for app resources.

Thank you.

**Comment by iJungleboy** [comment]
@MS-BSI you are responding to the wrong ticket. But somet things are ok, others not. 

1. seeing an empty dialog is expected, because your app doesn't have any settings to configure (the fields-count is 1) same for app-resources
1. The app-configuration on the other hand currently has 3 items. Please delete the 2 which are wrong, just so you won't run into trouble in future.

**Comment by MS-BSI** [comment]
Yes, the other one is closed and I thought the "global 2sxc-language settings" that I was looking for then that you asked me, where in the same tab, like before. This is why I opened an other ticket. Obviously no, and I found the new location via the "..." button !

**Some screenshots**
Form view displayed when we are in the french language : https://imgur.com/le11ave
Same form view but displayed when we are in the turkish language, no more selectbox : https://imgur.com/9HaPzQp
Note : Like I said before, if I open two browser tabs and navigate to the turkish version on a second tab, the first tab (still in french) suddenly causes the same bug, as if 2SXC kept in memory the last access made (turkish version). The reverse is also true : a refresh of the french browser tab makes the turkish tab works.


2. I removed some duplicates and left what seemed to be different lines, here's what I have, what to keep?
https://i.imgur.com/J6e5OEW.png

**Comment by MS-BSI** [comment]
New information, if I change the browser language cookie to "tr-TR", the bug occurs (without any page reload !) and if I revert to any other language ("fr-FR" for example), the list box is showed again.

**Comment by MS-BSI** [comment]
@iJungleboy : Simple way to reproduce the bug.

1. Install DNN 8.0.4 (blank EN website)
2. Add turkish language (Turkish (Turkey))
3. Update host configuration to allow content localisation
4. Update site languages page to allow localized content
5. Install 2sic 11.10.016. 
7. Add Content module on english homepage + install recommended content package
8. Add basic content layout
9. Configure 2 languages in 2Sic options ([screenshot](https://i.imgur.com/oChSXTN.png))
10. Copy module on the TR homepage (via page settings)
11. Form on EN website is OK, for boths languages tabs (look at the Heading selectbox or the text editor) while the TR form is broken (no select box + no text editor). ([screenshot EN](https://i.imgur.com/X5vNuIs.png) + [screenshot TR](https://i.imgur.com/uDUSjZC.png))

I can email you the URL of our fresh demo instance if you want.

**Comment by MS-BSI** [comment]
New useful informations :

- Bug still persists after DNN 8.0.4 to DNN 9.8.0 upgrade.
- I confirm that any (at least the ones tested) other language added to the website works, only the "tr-TR" seems to be bugged.
- If I compare the 2 **/api/2sxc/cms/edit/load?appId=2** requests (the TR one and any other one) I have a major difference for dropdown objects :
`0	Object { Name: "HeadingType", Type: "String", InputType: "string-dropdown", … }`
`0	Object { Name: "HeadingType", Type: "String", InputType: "string-default", … }`

More interesting fact and I talked about it earlier, modifying the request and sending it again by only modifying the culture-code present in the "Cookie" header, allows the request to work !
Thus changing "language=tr-TR" to "language=en-US" (or any other culture-code) makes the request functional.

I will not be able to go further for the debug, it seems to be internal to the 2Sic code and linked to the culture-code "tr-TR" (at least).

**Comment by iJungleboy** [comment]
Thanks for all the updates, very appreciated. 

We're in the middle of a complex feature which will absorb us for about another week, but we'll look at it then. If new findings pop up, please keep us posted.

**Comment by iJungleboy** [comment]
Just fyi: we just released 11.11 which fixes various DNN language detection issues. I'm not sure how it affects your issue but it could be related. Could you test?

**Comment by MS-BSI** [comment]
Hi Daniel,

Unfortunately the problem persists (tested on DNN 8.4.0 and DNN 9.8.0) :(
I can send you a link to the test website if needed.

**Comment by iJungleboy** [comment]
@MS-BSI So I don't usually do user support - but in this case I think it might affect others too so yes, pls send me a user login (host would be preferred) to info-you-know-2sxc.org

**Comment by iJungleboy** [comment]
It seems to be that the i18n tries to load the turkish file and runs into a 404. That seems to break everything. I'm researching a fix.

**Comment by MS-BSI** [comment]
If we are talking about the same thing then I had already looked at this and copy / paste the en.js file that I had renamed, the file was then correctly loaded and the bug was still present.
Moreover the bug seems to be on the server side because the module doesn't work correctly in display either (no image for example on the demo / debug site).

**Comment by iJungleboy** [comment]
So at first I thought it was the JS because it gave so many errors on 404. I now implemented something to capture that correctly #2290 

But it still doesn't fix the issue. Apparently the backend is really giving the wrong configuration. The input-type information for wysiwyg is missing in this example from your site:
![image](https://user-images.githubusercontent.com/5321186/102008624-44641180-3d32-11eb-862b-54ccf23779fd.png)

I'll try to figure that out.

**Comment by MS-BSI** [comment]
Yes, I mentioned it on this post : https://github.com/2sic/2sxc/issues/2261#issuecomment-737745887

Thanks for following up on the bug.

**Comment by iJungleboy** [comment]
Still working on it - new strange finding: on Arabic UAE it works, but Turkish it doesn't (also on my system)...

**Comment by iJungleboy** [comment]
I believe I found the cause - it was nasty. 

Apparently Turkish has a different lower case `i` which  `ı` (notice no dot on top). This resulted various places where our code uses `ToLower()` before comparing values - and it only caused trouble if there was an uppercase `I` in the original - like if a field was `InputType` which was converted to ` ınputtype`. Then it couldn't find the field, so it assumed no data was found. 

I changed all our code to not use `ToLower()` but `ToLowerInvariant()` which seems to work now.

I've attached a temporary build of the upcoming release - could you please test it elsewhere?
[Uploading 2sic_2SexyContent_11.11.02_Install.zip…]()

**Comment by MS-BSI** [comment]
Nice catch, we had the same behaviour inside the turkish website with a forced replacement for all "i" characters in URLs to avoid any problem.

Strange thing that the culture code impacts the lowercase function, nice to have a workaround with the Invariant one !
It worked before, so there must have been a change in the code in the meantime.

Seems to be OK now, thx ;)
