### ISSUE TITLE
"Replace with other Content" not working on some apps after 7.2.2 upgrade

### ISSUE THREAD

**Issue by grayspace** [2sic/2sxc#314]
I just upgraded from ~~7.0.2~~ **(edit: 7.2.0)** to 7.2.2, and everything seems to be working fine except I have some Apps (not all) that crash when I try to use the "Replace with other Content" feature.

The error I'm getting when I click the "Replace" button is:

``
DotNetNuke.Services.Exceptions.PageLoadException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at ToSic.SexyContent.SettingsWrapper.<Page_Init>b__0(KeyValuePair`2 p)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Web.UI.WebControls.ListControl.PerformDataBinding(IEnumerable dataSource)
   at System.Web.UI.WebControls.ListControl.OnDataBinding(EventArgs e)
   at System.Web.UI.WebControls.ListControl.PerformSelect()
   at System.Web.UI.WebControls.BaseDataBoundControl.DataBind()
   at ToSic.SexyContent.SettingsWrapper.Page_Init(Object sender, EventArgs e)
   at System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e)
   at System.Web.UI.Control.OnInit(EventArgs e)
   at System.Web.UI.UserControl.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at System.Web.UI.ControlCollection.Add(Control child)
   at DotNetNuke.UI.Modules.ModuleHost.InjectModuleContent(Control content)
   at DotNetNuke.UI.Modules.ModuleHost.CreateChildControls()
   at System.Web.UI.Control.EnsureChildControls()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   --- End of inner exception stack trace ---
``

**Comment by iJungleboy** [comment]
Thx for the feedback. You you be more precise - does the error occur in the lightbox/iframe or where?
Maybe you could export such an app and mail it to me on info ... 2sxc...org?

**Comment by iJungleboy** [comment]
...and maybe create a short screen-cast where you raise the error?

**Comment by grayspace** [comment]
Here is some more info, and I also will email you an export of the app. Wish I knew more to be helpful!

This happens when I go to edit a list item, either through the DNN "pencil" edit dropdown, or the 2sxc edit button.

From the Edit Item dialog, I click on the "Replace with other Content" button...

![image](https://cloud.githubusercontent.com/assets/5733194/9089925/3dd6cbdc-3b5d-11e5-89eb-a09ec3ee4133.png)

Then...

![image](https://cloud.githubusercontent.com/assets/5733194/9089956/72c504f8-3b5d-11e5-8107-b67d5dc90f75.png)

And here's what is in the console (unsure if it's related)...

![image](https://cloud.githubusercontent.com/assets/5733194/9091363/76f34e06-3b65-11e5-8a19-e40ee074a938.png)

Server Event Viewer shows two errors...

``
An unhandled exception occurred and the process was terminated. Application ID: /LM/W3SVC/4/ROOT Process ID: 6300 Exception: System.Threading.ThreadAbortException Message: Thread was being aborted. StackTrace: at System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) at System.Web.Hosting.PipelineRuntime.ProcessRequestNotificationHelper(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags) at System.Web.Hosting.PipelineRuntime.ProcessRequestNotification(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags)
``

And...

``
Faulting application name: w3wp.exe, version: 7.5.7601.17514, time stamp: 0x4ce7a5f8
Faulting module name: KERNELBASE.dll, version: 6.1.7601.18409, time stamp: 0x53159a86
Exception code: 0xe0434352
Fault offset: 0x0000c42d
Faulting process id: 0x189c
Faulting application start time: 0x01d0cf9d00c7ad7e
Faulting application path: C:\Windows\SysWOW64\inetsrv\w3wp.exe
Faulting module path: C:\Windows\syswow64\KERNELBASE.dll
Report Id: 72b3d49e-3b90-11e5-8398-f8b1569cf436
``

And here is some more info shown in the DNN Event Viewer for the error previously posted...

``
RawURL:/HOME/ctl/settingswrapper/mid/492/ToSIC_SexyContent_ContentGroupGuid/2b3f4aa2-b1e1-4a0e-baf4-3fecbcf60e72/SortOrder/2/ItemType/Content?popUp=true&ReturnUrl=%2f%3fctl%3deditcontentgroup%26mid%3d492%26returnUrl%3dhttp%253A%252F%252Flocalhost%253A8500%252F%26cultureDimension%3d3%26sortOrder%3d2%26contentGroupId%3d2b3f4aa2-b1e1-4a0e-baf4-3fecbcf60e72%26popUp%3dtrue
AbsoluteURL:/Default.aspx
AbsoluteURLReferrer:http://localhost:8500/?ctl=editcontentgroup&mid=492&returnUrl=http%3A%2F%2Flocalhost%3A8500%2F&cultureDimension=3&sortOrder=2&contentGroupId=2b3f4aa2-b1e1-4a0e-baf4-3fecbcf60e72&popUp=true
UserAgent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.130 Safari/537.36
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:65f2950e-fb0d-47f3-a6ac-ee5489352ca3
InnerException:Object reference not set to an instance of an object.
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:ToSic.SexyContent.SettingsWrapper.<Page_Init>b__0
``

At that point either I can "x" out of the dialog and go back to the refreshed page, or the entire site will crash.

**Comment by grayspace** [comment]
FYI - I just tried rolling back to my previous DNN setup with 2sxc 7.2.0, and I still get the error. So it doesn't appear to be limited to 7.2.2.

**Comment by joshgk00** [comment]
I'm also seeing this issue with just regular Content Types as well. When trying to add something to a List that was previously removed, I'm getting the same error about the Content Type not being allowed.

**Comment by iJungleboy** [comment]
Just a new idea: could it be that you have dnn 7.4.1? Because that has a URL-Bug, which could easily cause this issue. To verify, pls try:
If it works inline (see pic), but not from the dialog, then it's 99% that problem
(https://cloud.githubusercontent.com/assets/5321186/9175770/bacb0b48-3f87-11e5-82b5-3c707de48dfe.jpg)

If you modify the url which causes the error to appear - by removing the entire returnurl=...parameteork, then it is this issue. So take your original (a bit like this: /en/Home/ctl/settingswrapper/mid/420/ToSIC_SexyContent_ContentGroupGuid/5bf76130-b386-4848-9f17-aae567d50cf6/SortOrder/0/ItemType/Content?popUp=true&ReturnUrl=%2fen%2fHome%2fctl%2feditcontentgroup%2fmid%2f420%2fsortOrder%2f0%2fcontentGroupId%2f5bf76130-b386-4848-9f17-aae567d50cf6%3freturnUrl%3dhttp%3a%2f%2f2sxc.org%2fen%2f%26popUp%3dtrue) and kill the returnurl so it's a bit like this (/en/Home/ctl/settingswrapper/mid/420/ToSIC_SexyContent_ContentGroupGuid/5bf76130-b386-4848-9f17-aae567d50cf6/SortOrder/0/ItemType/Content?popUp=true)
![2015-08-10_17-43-26]

**Comment by grayspace** [comment]
I'm running DNN 07.03.04. And unfortunately, both the dialog and inline replace content buttons crash it.

**Comment by EzraM** [comment]
Also running into this issue. Removing ReturnUrl did not fix.

Url:
`http://<some url>/excess-liability-insurance/ctl/settingswrapper/mid/1662/tosic_sexycontent_contentgroupguid/195eadcd-e5e7-452e-a69e-c63fe7379563/sortorder/0/itemtype/content?popUp=true`

Error:
 `Type content not allowed`
```
   at ToSic.SexyContent.ContentGroup.get_Item(String type)
   at ToSic.SexyContent.SettingsWrapper.Page_Init(Object sender, EventArgs e)
   at System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e)
   at System.Web.UI.Control.OnInit(EventArgs e)
   at System.Web.UI.UserControl.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at System.Web.UI.ControlCollection.Add(Control child)
   at DotNetNuke.UI.Modules.ModuleHost.InjectModuleContent(Control content)
   at DotNetNuke.UI.Modules.ModuleHost.CreateChildControls()
   at System.Web.UI.Control.EnsureChildControls()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
```

DNN: 7.4.0
2sxc: 7.2.2

**Comment by iJungleboy** [comment]
@grayspace - thanks for the demo app. I can reproduce the issue, but I can't corner it yet. But this will help...

**Comment by iJungleboy** [comment]
I figured it out! 
So first of all - thanks @grayspace for the demo app, it really helped me debug it. 

There a problem with the data - this is how it probably happened:
1. you created some records
2. then you added a new column - for example in this case the column BranchOrPageName - and defined that as being the new title
3. then you added more records - but some of the old ones never got data in that column

Because of this, when the system tried to offer the drop-down field, it failed - because it couldn't find the title: 
![image](https://cloud.githubusercontent.com/assets/5321186/9260585/e3afa6c6-4208-11e5-818b-50530020306b.png)

In the data you can also see these columns are empty (of course you can't tell if it's blank or not existing): 
![image](https://cloud.githubusercontent.com/assets/5321186/9260596/f5037470-4208-11e5-9b8a-4517fd5b53c7.png)

So what I'll try to do is improve 2sxc that it won't break down...
...but you can quickly work around the problem by just ensuring that all your records have a title. 

Hope this helped - also for the others who had the same issue!

**Comment by iJungleboy** [comment]
Update: I just wrote the code to fix it #316 
That's the good news. There's a bit of bad news: I found a second bug :(
So for most cases the previous bug was the right one - and you can work around it. But the replace-button actually fails on list-headers. Reason is that in the old data-model the header-item had an index of -1, but now it doesn't work that way any more. So I'll have to look into that separately.

**Comment by joshgk00** [comment]
I’m still seeing this issue with my Content Type. I haven’t made any changes to the content type other than upgrading to 7.2.0. So it seems the workaround wouldn’t apply in my case. Any other thoughts as to what the problem could be?

**Comment by iJungleboy** [comment]
Try upgrading to the newest 7.x. We had some difficulties upgrading which should be fixed in the newest release.

**Comment by joshgk00** [comment]
The issue still exists even after upgrading to 7.2.2

**Comment by iJungleboy** [comment]
Solved in 7.2.3

**Comment by EzraM** [comment]
DNN: 7.4.1
2sxc: 7.2.3

Cannot replace content. Have a small sample app -- how would I share it?
Here's the app:
1) ContentType and template with 2 text values
2) ContentType record with 2 sample values
3) Create content module, add random values
4) Edit content module, click 'Replace with Other Content'. Doesn't work.

**Comment by joshgk00** [comment]
I'm still seeing an issue with this in 7.2.3 when trying to replace content in a list

AbsoluteURL:/Default.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:73edaecc-c501-4a53-8017-42b5d530b3c7

AssemblyVersion:7.4.0

PortalId:0

UserId:1

TabId:117

RawUrl:/test/ctl/settingswrapper/mid/477/tosic_sexycontent_contentgroupguid/923d68cd-8de3-4d75-b028-8c81c1945fec/sortorder/2/itemtype/content?popUp=true&ReturnUrl=%2ftest%2fctl%2feditcontentgroup%2fmid%2f477%2fsortorder%2f2%2fcontentgroupid%2f923d68cd-8de3-4d75-b028-

Referrer:http://pyramidint.runsonawesome.net/test/ctl/editcontentgroup/mid/477/sortorder/2/contentgroupid/923d68cd-8de3-4d75-b028-8c81c1945fec?popUp=true&ReturnUrl=%2ftest%2fctl%2feditlist%2fmid%2f477%3fpopUp%3dtrue

UserAgent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36

ExceptionHash:MWwF0lu+/FCvup6GzqB5Kw==

Message:Type content not allowed

StackTrace:

InnerMessage:Type content not allowed

InnerStackTrace:

   at ToSic.SexyContent.ContentGroup.get_Item(String type)
   at ToSic.SexyContent.SettingsWrapper.Page_Init(Object sender, EventArgs e)
   at System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e)
   at System.Web.UI.Control.OnInit(EventArgs e)
   at System.Web.UI.UserControl.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at System.Web.UI.ControlCollection.Add(Control child)
   at DotNetNuke.UI.Modules.ModuleHost.InjectModuleContent(Control content)
   at DotNetNuke.UI.Modules.ModuleHost.CreateChildControls()
   at System.Web.UI.Control.EnsureChildControls()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
