### ISSUE TITLE
Non-Admin Page Editor - Error 403 Editing Inner Content

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc#3234]
### Current Behavior
Everything works fine for Administrator or Host. We have added the Role named "Site Manager" and on the **Page**, that Role has both View and Edit permissions.
 
The Accordion has 3 sections, each container 1 inner content: The Content App using a Links Content Type and View. Changing the View makes no difference. When the Site Manager tried to Add or Edit one of the Link items (via the 2sxc standard Toolbar buttons), we get an error:

![image](https://github.com/2sic/2sxc/assets/653301/10d3f9e3-eb9a-4087-bb33-88a0973638d5)
 
And in the DevTools console:

![image](https://github.com/2sic/2sxc/assets/653301/9ade2946-0f6a-4bb1-8e30-2dc2f85e261b)
 
### Expected Behavior
The User in the Role with Page Edit permissions should be able to both Add and Edit new inner content items.

You can see in the console error that appId=2 (the Content App) is where the permissions might need to be set. But a) the Content App doesn't support this and b) we have not had to do this in the past; 2sxc v13 and v14 (from doing a quick check where this is working).

### Your environment
We are using 2sxc v16.09.00 and the Content App is 14.9.1, Accordion 4.3.1 

* **Browser:** all/any
* **DNN:** all | 9.13.01 | 9.13.00
* **Hosting platform:** all | IIS | azure | other
* **Language:** any/all | English | any

**Comment by jeremy-farrance** [comment]
Bump. This is fairly urgent since the client found and reported it.

**Comment by iJungleboy** [comment]
This _could_ be related to #3258 which should be fixed in a few hours. 

pls test again with v17.02 when released.

**Comment by jeremy-farrance** [comment]
Tried 2sxc 17.01.02 and then 17.01.03 and sorry, no, **not fixed yet.** Reminder, you can edit the Accordions, its this error is thrown when you edit the inner content items. I do notice the 403 error is a little more verbose.

![image](https://github.com/2sic/2sxc/assets/653301/24094b93-0929-430a-a5a3-46b94098f3e2)

**Comment by iJungleboy** [comment]
So the problem is pretty clear. 

When users work on inner content and switch Apps, they are basically capable of doing anything - including maybe accessing apps which they should not. 

I assume that in this case this is fine, but we can't open it for everybody because that could result in some nasty surprises. 

We created a new feature which allows this, but does warn users that there are security implications:

![image](https://github.com/2sic/2sxc/assets/5321186/d826d4a5-08bc-4941-b129-b30251b455ad)

![image](https://github.com/2sic/2sxc/assets/5321186/1388ad42-3fac-46ba-aaf3-8f4c66d258bd)

Should be in 17.01.04+

**Comment by jeremy-farrance** [comment]
Okay, so two questions.
 
1. can you give me an example of the risk? What nasty thing could a user do? Just edit content they maybe shouldn't? Or something worse?
2. is there any way to solve this in code or with a more detailed setup using permissions? In other words, your solution here seems to be, "make the host click a checkbox so they know its not secure, but really need to do this." If that is correct, is there a better way to accomplish this?

**Comment by iJungleboy** [comment]
If your editor is restricted then you probably had a reason for doing this. 

If you goal was that she could only work in one specific module (eg. News, but not Real-Estate-Listings) then she could add an inner module Real-Estate-Listings and could then edit content in there which was possibly not intended at all. 

As of now there is no way to restrict which apps can be added to inner content.
