### ISSUE TITLE
Old Code throwing an unexpected NullReferenceException after upgrading to 2sxc 17.01.01

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc#3260]
### I'm submitting a

[x] bug report

### ...about

[x] Razor templating
[x] other / unknown

### Current Behavior / Expected Behavior

I found another case where v17.x is not working with 'old code.' I think its from a 2019-20 version of the Content App; Shared/_Assets.cshtml which was called like this from the template "above"
```
@Html.Partial("../Content/Accu/_Shared--Assets.cshtml", new { parts = "datatables"})
```

This file has no @inherits, so that means its defaulting all the way back to ... I don't remember?

Here is the start of the code part, line 31 is the `var parts = partsList.Split...`
```
@{
  string partList = PageData["parts"];
  var parts = partList.Split(',').Select(s => ((string)s).ToLower().Trim()).ToArray();  // line 31
  var all = parts.Contains("all");
  var styles = all || parts.Contains("styles");       // these are 2sxc Content App stuff
  var scripts = all || parts.Contains("scripts");     // these are 2sxc Content App stuff
  // not included in `all`
  var fancybox = parts.Contains("fancybox");   
  var glidejs = parts.Contains("glidejs");            // untested
  var slickjs = parts.Contains("slickjs");
  var sweetalerts = parts.Contains("sweetalerts") || parts.Contains("sweetalerts2");
  var datatables = parts.Contains("datatables");  
...
```

The full error is:
```
Error: System.NullReferenceException: Object reference not set to an instance of an object. at 
ASP._Page_Portals_0_2sxc_Content_Accu__Shared__Assets_cshtml.Execute() in 
C:\HostingSpaces\ ... \www\Portals\0\2sxc\Content\Accu\_Shared--Assets.cshtml🎯:line 31 at 
System.Web.WebPages.WebPageBase.ExecutePageHierarchy() at 
System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) at ToSic.Sxc.Dnn.Razor.DnnRazorEngine.Render(RazorComponentBase page, TextWriter writer, Object data) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Razor\Dnn\Razor\DnnRazorEngine.cs:line 103 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at ToSic.Sxc.Dnn.Razor.DnnRazorEngine.Render(RazorComponentBase page, TextWriter writer, Object data) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Razor\Dnn\Razor\DnnRazorEngine.cs:line 110 at ToSic.Sxc.Dnn.Razor.DnnRazorEngine.RenderImplementation(RazorComponentBase webpage, RenderSpecs specs) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Razor\Dnn\Razor\DnnRazorEngine.cs:line 121 at ToSic.Sxc.Dnn.Razor.DnnRazorEngine.RenderPage(String templatePath, Object data) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Razor\Dnn\Razor\DnnRazorEngine.cs:line 229 at ToSic.Sxc.Dnn.Razor.HtmlHelper.Partial(String path, Object data) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Razor\Dnn\Razor\HtmlHelper.cs:line 70
```

### Your environment

* **2sxc version(s):** 17.01.01 (just released about an hour ago)
* **Browser:** all/any
* **DNN:** v9.13.02
* **Hosting platform:** IIS
* **Language:** any/all

**Comment by iJungleboy** [comment]
Could you investigate further? I'm almost certain that this is not due to the upgrade to v17.

Could you output the `partList` variable? I assume it should contain a string containing names of parts to add -eg `styles,scripts` or something. 

Basically the PageData is a built-in feature of Razor and the code looks like it's not using any 2sxc objects.

**Comment by iJungleboy** [comment]
I have a guess, but I'm not sure if I can replicate.

Would it be possible to send me the problem-app to info 2sxc org as a zip or wetransfer?

**Comment by iJungleboy** [comment]
@jeremy-farrance So I think it is a bug we introduced, as I noticed we're also doing some magic to make sure **HotBuild** works. This could interfere with parameters being passed in. 

I may have already fixed it with #3264 but I'm not 100% sure.

Could you either send me the code, or at least tell me what the `@inherits` is of the calling page (so the "parent")?

**Comment by iJungleboy** [comment]
I did some tests and believe it's fixed in 17.01.03 to be released in a few minutes. 

Pls test and confirm, thx!

**Comment by jeremy-farrance** [comment]
Its not fixed, but I found the same code working in other places. The problem is, in this ONE case, the call from the page above:
```
@Html.Partial("../Content/Accu/_Shared--Assets.cshtml", new { parts = "datatables,sweetalerts" } )
```

_PageData["parts"] is null on arrival._ No idea why, but I've spent too much time on this and need to move on. The app is not something I can share easily.
 
If you have any ideas on why PageData["parts"] is not working, I'd be happy to test any workarounds you can think of. Maybe there is an @inherits I could add at the top of the page?

**Comment by jeremy-farrance** [comment]
Oh, missed your 1 question. And its a big clue I think. The parent/calling page is:
```
@inherits Custom.Hybrid.RazorTyped
```
and the receiving page, as I mentioned above, has no @inherits.

**Comment by iJungleboy** [comment]
Thanks, I can reproduce now...

**Comment by jeremy-farrance** [comment]
If it helps, , my opinion is, I no longer think this needs to be fixed. My situation... upgrading a View to .RazorTyped while leaving a Html.Partial() as an ancient inherits (default) is probably an edge case you can ignore (unless its easy and obvious how to fix it).

**Comment by iJungleboy** [comment]
Thx.

I agree that it's really an edge case and could be ignored. 
Since it affects an App which we created, we must fix it :(

But I found a way, and it's fixed in the next release.
