### ISSUE TITLE
[BUG]  Editing Queries Fails Manage-Apps for All 2sxc Queries - 2sxc 19.03.01 (and .02)

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc#3585]
### Bug Affects...
[x] edit experience / UI
[x] admin experience UI

### Current Behavior

After adding, editing and saving Visual Queries (which works at first), we add another new one filling out just the Query Name (we named it, "EDN Event Articles by Params", though I doubt that matters), clicked save, then clicked on the new Query's Name field to open the Visual Query editor in a new tab. The tab opens, the page is blank/white. Reloading the new tab makes no difference.

This is the error that appears in the Chrome DevTools/Console log - **note that this is in the NEW TAB** that opens for the Visual Query edit UI

![Image](https://github.com/user-attachments/assets/85f2c9e5-9699-4484-a74a-52fbc0869121)

### Expected Behavior

We should be able to Edit Visual Queries like normal.

### To Reproduce (Steps, Videos, Screenshots, Apps)

1. New DNN 9.13.07, install 2sxc 19.03.01 and get it working (CodeDom 3.6, etc.)
2. Install an existing app (we chose Blog) and get it on a page
3. Go to Admin, then the Queries (tab) UI
6. Click any query's name to Edit...

New tab opens, stays blank, error in Console of new tab

**Comment by jeremy-farrance** [comment]
### I have to mention that this is really urgent for us, this is an in-development project and it would require quite a bit of effort to work around NOT being able to use the Visual Query Edit UI. I am available (contact me via Discord) if you have trouble reproducing this. Its happening on multiple projects now and easy to reproduce in a clean local install of DNN+2sxc.

**Comment by jeremy-farrance** [comment]
## Additional weirdness - Please read, especially the item at the bottom!!

Once the problem happens and all attempts in any app to edit any existing Query fails, we tried the following to get it working again, **all failed**:

- Restarted DNN (app pool)
- Restarted the browser and also tried in a different browser (Edge and Firefox)
 
## Weird way to get it working again... and then fail again (WTF?)

After it fails and you are ready to give up, try this:

- Install a new 2sxc App that you know has some Queries
- Get it on a page and working
- Go to App Admin, Queries, edit one of Queries, IT WORKS
- Now go back to the other App and try to edit one of the queries that failed before, it fails
- Now go back to your newly installed App, edit one of the Queries, NOW IT FAILS

**Comment by iJungleboy** [comment]
I need to know where the failure happens. 

If a "broken" app is installed on another DNN, is it still broken? if yes, could you upload such an app to speed up testing?

**Comment by jeremy-farrance** [comment]
Just FYI, this continues to happen once or twice each work day here. No reproducible pattern. I've adjusted the steps above to eliminate some things that made no difference.

**Comment by jeremy-farrance** [comment]
Since we have this happening for two people on two different machines in 3 projects with any browser, I just want to recap the key observations. 

- See screenshot above, the error that happens is while Angular (core js) is executing on the front end
- This is happening on real in-progress projects that started life with DNN v9.13.07 and 2sxc 18.6.1... then upgraded to 19.3.0 LTS then 19.3.1 LTS. The problem was first noticed after installing 19.3.1, these dev+staging projects run on remote (vps-style) servers in the cloud
- This is happening on clean+new deploys of DNN v9.13.07 and 2sxc 19.3.1 LTS, these projects are running locally on a Windows 11 machine
- We use CodeDom 4.1 (from DNN v10), but the problem happens with CodeDom 3.6, so I no longer think this is a factor
- Once the problem happens, it is no longer possible to edit any Visual Query _in any app in this DNN instance_. 
- After it happens, if you come back ~4 hours later or the next day, usually, but not always, the problem has fixed itself
- This happens in any browser, any version (we are mostly using Chrome latest or latest-1)
- Deleting all cookies and browser data for the site (and logging in again) does not fix the problem (e.g. in Chrome, chrome://settings/content/all, search for the URL of your site, etc)

**Comment by jeremy-farrance** [comment]
### One final un-scientific observation

If you go into DevTools, Console, **Network** tab and slow things down > **set the Throttling down to 3G** (or Slow 4G), the problem is MORE LIKELY to happen.

But then again, I also have the impression its more likely to happen in the morning than in the afternoon. :/

**Comment by jeremy-farrance** [comment]
Note: I don't do Angular at all, so I might be saying things (about modules or routes) that are wrong...

After a week of playing with this on and off and at different times, my general impression is that this is a timing issue. Something that normally (lazy) loads fast-enough is sometimes a little late (not there when needed) and (Angular?) routes fail. 
 
When launching in to a new tab (/desktopmodules/tosic_sexycontent/dist/ng-edit/), was anything about the loading modules or routes changed recently? Maybe in relation to the newer ctrl-click feature that forces various front-end edit UIs in to a new tab?

**Comment by iJungleboy** [comment]
The timing thing could be a lead.

I don't think it's related to the open-link-in-new-window, because the query always opened in a new window. But we did refactor some services to use signals instead of Observables inside Angular.

It's possible that something wasn't done quite correctly. Maybe @paulpietzko could look at this next week?

**Comment by jeremy-farrance** [comment]
Tested again by upgrading a site from 2sxc 19.03.01 to v19.03.02. Same error. could not find any differences to what has been reported so far (above).

**Comment by jeremy-farrance** [comment]
After playing some more, I did get something new to happen. After the upgrade, the error happened immediately on the first Query I tried to edit. I tried a few more queries, all new tab > blank+error. Suspiscious of the "timing" issue I made note of the upgrade install happening at 10:01 am. I set a timer to try again after 20 mins. No diff, still broken. 

Then, I set another timer to try again after 10:31am... and presto, it started working again; I could edit a Visual Query and everything was working like normal for all queries!! So almost exactly 30 mins after the install of the 2sxc upgrade, suddenly the Visual Queries are working completely normal again.
 
_I hope this is somehow a helpful clue._

**Comment by paulpietzko** [comment]
@Dominikg77 is probably the better one to solve this.

**Comment by iJungleboy** [comment]
@jeremy-farrance we cannot reproduce this.

Any chance to show another JS console of the problem state? We think that the initial JS error you show is not relevant for this problem...

**Comment by jeremy-farrance** [comment]
Its still happening. I've eliminated thinking it might be a) extensions in the browser (happens in both Edge and Chrome with no extensions) and b) the server running slow; happens on very fast servers with very few projects.
 
I tried again just now and same error in the new tab's DevTools.
 
I am not sure yet what else to offer. Its a severe hinderance for us at the moment on projects, but we are slowly working around it. I hope I notice new details soon, thanks - Jeremy

**Comment by iJungleboy** [comment]
Could you also post the URL you see in the browser? I have a feeling something is wrong there...

In which case the problem is not the query dialog, but actually the link which goes to that query, which may be wrong...

@paulpietzko could you check? in the screenshot the URL doesn't actually look like it's going to the right place - at least not to the query designer. 

![Image](https://github.com/user-attachments/assets/4b408f65-3dff-4d63-b265-2248588facc5)

**Comment by jeremy-farrance** [comment]
Here is the url/address from hovering on the Query name (before):

`https://dev.iser-society.org/desktopmodules/tosic_sexycontent/dist/ng-edit/?pageId=54&portalId=0#/3/v2/477/477/7/apps/list/query/1730`

Here is what resolves in the new tab (after):

`https://dev.iser-society.org/desktopmodules/tosic_sexycontent/dist/ng-edit/?pageId=54&portalId=0#/`

As you can see, the # part of the query from the first link, is what is throwing the noMatchError in DevTools console:

![Image](https://github.com/user-attachments/assets/c6b1cd67-830e-4822-8f7c-6ee6bf516c83)

**Comment by iJungleboy** [comment]
I tried but can't reproduce the problem. 

But here some insights: the problem is not the query designer - it's the page / dialog that came before, where you clicked on the link. That link is incorrect. 

Could it be that you have 2 different ways to get to the query, and one works, the other one does not?

Which dialog were you on, when you opened the query designer? Something must be wrong there.

**Comment by iJungleboy** [comment]
I added some more logging to look at together (it's quite complicated so hard to explain here).
But the important question is more where you started from, that will bring us further...

**Comment by iJungleboy** [comment]
I still need the URL you were on before you clicked - not the url you were going to click, but the list or whatever you were on before.

Because obviously that url is the relative url used to create the final link - which is then wrong.

**Comment by jeremy-farrance** [comment]
Ok, after reading your latest insights, here is the proper answer to your question as well as a bit more detail on the steps we are using to get to the queries when they fail (since it seems like it could be a factor).

Here is the URL of the page we are on
https://dev.iser-society.org/Become-a-Member

Often, the query we are editing is not in an app on the current page, so most of us are in the habit of going to any 2sxc app (even the Content app), then:

- "spinning the 3-dot dial" to the 3rd group
- click "manage apps"
- click the "Apps" tab
- click (go into) an App (choosing Blog 6.17.1 this time)
- click the "Queries" tab
- then just click on one of the Queries' Name field
- immediately opens new tab...

And displays a blank white page.
https://dev.iser-society.org/desktopmodules/tosic_sexycontent/dist/ng-edit/?pageId=54&portalId=0#/

**Comment by jeremy-farrance** [comment]
Just in case there is a helpful visible detail:

![Image](https://github.com/user-attachments/assets/a04102ed-0597-482b-b544-5f1f5e5484d9)

![Image](https://github.com/user-attachments/assets/123e29cb-9bd1-4d58-b3b0-137b25fbf00e)

**Comment by iJungleboy** [comment]
all right, we have the culprit ;)

**Comment by iJungleboy** [comment]
fixed in next release - for now, just use the direct access ;)

**Comment by RaulZU-ceu** [comment]
Hello.
After installing version 21.03.00, I am still the same issue, and this is the error I'm getting in the DevTools console.

<img width="635" height="238" alt="Image" src="https://github.com/user-attachments/assets/2d5b317e-6929-4a09-8920-cd4c0f943c75" />

The error occurs when using the “short way,” the “long way,” and in any app—whether in the same tab or a different one.

These are the URLs where the links I’m clicking are locatedThese are the URLs that I click from.

<img width="811" height="32" alt="Image" src="https://github.com/user-attachments/assets/c48088ea-0d35-49c8-8af4-99b5fa4f6041" />

<img width="715" height="30" alt="Image" src="https://github.com/user-attachments/assets/e6518cdb-7c1d-420c-bc33-e1299ae4ce6b" />

It's a development server in DNN version 10.01.01

If there’s anything else I can check, just let me know. Thanks.

**Comment by jeremy-farrance** [comment]
@RaulZU-ceu, are you able to post this as a new issue soon?
