### ISSUE TITLE
upgrade 7.02.03 to 8.00.01 defined drop-downs are gone

### ISSUE THREAD

**Issue by Frankwalraven** [2sic/2sxc#401]
After the upgrade from 2sxc to 8.00.01 for all the fields the type (Fields.Table.InputType) is unknown, So also all the drop-down menus are gone. Also after set the set Fields.TitleEdit on drop-down the drop-downs are not back.

**Comment by iJungleboy** [comment]
Could you give a screenshot? what language is your UI?
Thanks,Daniel

**Comment by Frankwalraven** [comment]
Hi Daniel,
The language of the user interface is Dutch
Here is a screenshot



Met vriendelijke groet,
Perfocus

Frank Walraven







Perfocus w Ligusterweg 3 w 6601 HL  Wijchen w Telefoon: +31 (0)24-6690593
Mobiel: +31 (0)6 20398125 w Mail: f.walraven@perfocus.nl <mailto:f.walraven@perfocus.nl> w Skype: frankwalraven


Deze e-mail en eventuele bijlagen bij deze e-mail zijn uitsluitend bestemd voor de door de afzender vermelde geadresseerde(n). Indien deze e-mail niet voor u bestemd is en/of eventuele bijlagen bij deze e-mail niet voor u bestemd zijn, verzoeken wij u vriendelijk deze onmiddellijk te verwijderen, de ontvangst ervan onmiddellijk telefonisch aan ons te melden en de inhoud ervan niet aan anderen bekend te maken. Bekendmaking en gebruik van de inhoud van deze e-mail en eventuele bijlagen bij deze e-mail zonder toestemming van de afzender of de door de afzender beoogde geadresseerde kan onrechtmatig zijn. PerFocus accepteert geen enkele aansprakelijkheid voor het gebruik van de informatie in dit e-mail bericht.

**Comment by iJungleboy** [comment]
can't see screenshot - pls upload directly in github

**Comment by Frankwalraven** [comment]
![pastedgraphic-1](https://cloud.githubusercontent.com/assets/13934402/10731999/4f64472c-7bf8-11e5-9026-0cff7dad22eb.png)

**Comment by iJungleboy** [comment]
Thanks. So this is clearly an i18n issue, angular-translate. Do you think you can send the the url? right-click on the dialog and try to copy the (hidden) iframe-url and send it to me. It should look a bit like .../ui.html#zone=x&app=...&... (very long)
I need this to try to simulate your language-situation.

**Comment by iJungleboy** [comment]
I think I was able to reproduce the issue. the language-system currently tries to use your main language as the fallback, when it should use en-us (because that will exist for certain). Will look into it...

**Comment by iJungleboy** [comment]
fixed, will be in release 08.00.02

**Comment by Frankwalraven** [comment]
Problem in 8.00.02 is not fixed. Still the same issue
drop-down menus are still gone.
<img width="1366" alt="screen" src="https://cloud.githubusercontent.com/assets/13934402/10773532/26e4acec-7cfc-11e5-813d-298a3c8bf274.png">

**Comment by Frankwalraven** [comment]
http://gettingstarted.2sexycontent.org/router.aspx?DnnVersion=7.4.2.216&2SexyContentVersion=08.00.02&ModuleName=2sxc&ModuleId=541&PortalID=0&ZoneID=13&DefaultLanguage=nl-NL&CurrentLanguage=nl-NL&DnnGUID=177BA45E-611B-4214-8199-05D602F129C5

**Comment by iJungleboy** [comment]
You seem to have 2 issues 
1. Your core problem has to do with multi-language, as the column-heandings are also wrong. You will also see in fiddler that it is trying to get various files and getting a 404. The strange thing is we fixed the fallback in 08.00.02, so it should really show the headings in EN and it doesn't. Are you getting JS errors?

2. The "unknown" is not a problem itself. We introduced InputTypes in 8.0 and all previously created fields are "unknown" and will behave like they used to. You can click on the "unknown" and should get a dialog a bit like this - do you get this?
![30 add a field with the new type](https://cloud.githubusercontent.com/assets/5321186/10780320/6b44b81a-7d3c-11e5-8b83-2c60e851a88b.png)

**Comment by Frankwalraven** [comment]
Hi ,
Strange is that now the column-headings are displaced.  They are back. in the beginning they were not there.

About the input-types.
We saw already that you can change the unknown field-types to the old input type. But that is not really a nice solution. When we set a field that had before a drop-down to a drop down again, all the choices from the drop-down which where entered before are disappeared. So this mean we have to fill all the drop-down fields again with the old values.
I would suppose the old data get converted to the new structure and the old drop-downs will stay

Regards,
Frank


Met vriendelijke groet,
Perfocus

Frank Walraven
