### ISSUE TITLE
Impossible to add values in dropdowns

### ISSUE THREAD

**Issue by BravoSierra** [2sic/2sxc#414]
This seems to be application wide

**Comment by raphael-m** [comment]
Fixed in 08.00.03

**Comment by BravoSierra** [comment]
We still have this issue in 8.0.3. The dropdown values input is a text box (not a text area), so we cannot type more than one entry. The help is a messy HTML with HTML tags visible. It says one should enter one dropdown value per line, but that is not possible. We've also tried separators like | or ; but no luck

**Comment by BravoSierra** [comment]
No Raphael, we still cannot enter dropdown values

 

 

Benoît SARTON

 <http://www.bsi.fr/> www.bsi.fr

04 66 30 00 00

 

De : Raphael [mailto:notifications@github.com] 
Envoyé : lundi 9 novembre 2015 17:05
À : 2sic/2sxc
Cc : BravoSierra
Objet : Re: [2sxc] Impossible to add values in dropdowns (#414)

 

Fixed in 08.00.03

**Comment by BravoSierra** [comment]
Please reopen

 

Benoît SARTON

 <http://www.bsi.fr/> www.bsi.fr

04 66 30 00 00

 

De : Raphael [mailto:notifications@github.com] 
Envoyé : lundi 9 novembre 2015 17:05
À : 2sic/2sxc
Cc : BravoSierra
Objet : Re: [2sxc] Impossible to add values in dropdowns (#414)

 

Closed #414 <https://github.com/2sic/2sxc/issues/414> .
