### ISSUE TITLE
Improve un-cachning - V.8.5.2 Edit Template throw error - in Firefox

### ISSUE THREAD

**Issue by classmaxx** [2sic/2sxc#939]
i got an error, when i try to edit an template: 

Message: Der Controller http://dnn8.local/desktopmodules/2sxc/api/view/template/template?templateId=7288 konnte in den Namensräumen ToSic.SexyContent.WebApi.View nicht gefunden werden.

This happens on every template i try to open...

**Comment by iJungleboy** [comment]
I believe we had this issue briefly in 8.5.1, but not 8.5.2. Are you sure you're using the newest version? Pls check and get back to us, thx.

**Comment by classmaxx** [comment]
![version](https://cloud.githubusercontent.com/assets/22051626/18541827/e0056818-7b27-11e6-929a-061cfb4393fb.PNG)

**Comment by iJungleboy** [comment]
ok, thx. will check...

**Comment by iJungleboy** [comment]
Could you tell me which dialog you're trying to open? is it the code-editor, the template-properties or something else?

**Comment by iJungleboy** [comment]
Just fyi: we moved some code around - from the view/template to an app-asset-controller. So it's probably correct that this path doesn't work any more, I just don't know where it's still in use...

**Comment by classmaxx** [comment]
i'm trying to open the code-editor

**Comment by iJungleboy** [comment]
Ok. is fixed in 08.05.03 - should appear in a few days.

**Comment by mangiove** [comment]
Hi, this is still happening for me even with the 08.05.03 version...
Strange this is happening only using firefox.
Using google chrome it works fine :)

**Comment by iJungleboy** [comment]
Ok, will re-open.

**Comment by classmaxx** [comment]
For me everything works fine in FF and Chrome with 8.5.3

**Comment by iJungleboy** [comment]
I also ran a quick test with FF and it worked fine. Could you create a short screencast so we can see where it's failing?

**Comment by mangiove** [comment]
Hey there, I've done two short screencast, one about firefox and one about chrome. At the moment for me it is working fine only in internet explorer :(
Let me know if you need more informations
Thanks you

[screencasts.zip](https://github.com/2sic/2sxc/files/481063/screencasts.zip)

**Comment by mryckman** [comment]
Hello,

I'm getting the same error. Can I help provide anything? So far, it looks identical to what mangiove is reporting.

**Comment by mangiove** [comment]
Just a little update on this:
My collaborator using firefox says that everything is working editing contents templates in my portal.
For me at the moment only using ie is working.
Maybe the issue is something about cache?

**Comment by iJungleboy** [comment]
I'm also guessing it's caching. Of course it shouldn,t be, but it might be :(

Two ways to corner it - please tell us if this was the reason

1. Make sure the dialog is in a new window (you can also shift+click on all in-page toolbar buttons)
2. try ctrl+f5
3. if that still fails, it doesn't mean that it's not caching - because there is some script-lazy-loading which may still be screwed. in that case, please try...
  1. add &debug=true to the end of the url and then hit F5 again - this will load the unminified js, so most likely editions which have not been cached yet
  2. and/or go to you browser and clear the cache

did it help?

**Comment by mangiove** [comment]
Ok so it should be something caching...

1. Dialog is in new window
2. ctrl + f5 does not resolve the issue
3. Adding &debug=true to the end of the url and hitting F5 loaded correctly the template to edit.

I Hope that there is some fix to prevent this... :)
Thanks you!

**Comment by iJungleboy** [comment]
Ok - found out that:

1. there is already a cache breaker in use (2sxc version/build number)
2. but for some reason, the files are loaded again - without the version/build, which is then cached...
